'use client';
import {useEffect,useState} from 'react';
import {Search,Plus,ArrowRight,Clock3,X,Users,BriefcaseBusiness,History,ChevronRight} from 'lucide-react';
import {LABEL,PIPELINE,type Candidate,type Event,type Stage} from '@/lib/domain';
type SearchData={results:{candidate:Candidate;reason:string;score:number}[];message:string;understood:boolean};
const fmt=(v:string)=>new Date(v).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
export default function Home(){const [candidates,setCandidates]=useState<Candidate[]>([]),[query,setQuery]=useState(''),[searched,setSearched]=useState<SearchData|null>(null),[active,setActive]=useState<Candidate|null>(null),[events,setEvents]=useState<Event[]>([]),[modal,setModal]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[clock,setClock]=useState(0);
 async function load(){const r=await fetch('/api/candidates');setCandidates(await r.json());} useEffect(()=>{const timer=setTimeout(()=>{void load();setClock(Date.now())},0);return()=>clearTimeout(timer)},[]);
 async function search(value=query){if(!value.trim()){setSearched(null);return;}const r=await fetch(`/api/search?q=${encodeURIComponent(value)}`);setSearched(await r.json());}
 async function details(c:Candidate){const r=await fetch(`/api/candidates/${c.id}`);const d=await r.json();setActive(d.candidate);setEvents(d.history);}
 async function move(c:Candidate,stage:Stage){setBusy(true);setError('');const r=await fetch(`/api/candidates/${c.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({stage})});const d=await r.json();if(!r.ok)setError(d.error);else{await load();if(active?.id===c.id)await details(c);if(query)await search();}setBusy(false);}
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setBusy(true);setError('');try{const r=await fetch('/api/candidates',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:f.get('name'),email:f.get('email')})});const d=await r.json();if(!r.ok){setError(d.error);return;}try{await load();}catch{setError('Candidate was added, but the pipeline could not refresh. Reload to see the updated list.');}form.reset();setModal(false);}catch{setError('Could not confirm the candidate was added. Please check the pipeline before trying again.');}finally{setBusy(false);}}
 const shown=searched?.results.map(x=>x.candidate)??candidates;
 return <main className="shell"><header className="topbar"><a className="brand" href="#"><span className="logo"><BriefcaseBusiness size={19}/></span><span>hiring<span className="brandMuted">.desk</span></span></a><div className="topMeta"><span className="liveDot"/> Local workspace <span className="metaDivider"/> Associate hiring · 1 open role</div><button className="avatar" title="Recruiter">R</button></header>
 <section className="hero"><div><div className="eyebrow"><span/> RECRUITMENT WORKSPACE</div><h1>Good morning, Recruiter</h1><p>Here’s what’s happening with your candidates today.</p></div><button className="primary" onClick={()=>{setError('');setModal(true)}}><Plus size={17}/> Add candidate</button></section>
 <div className="summary"><div className="summaryTitle"><div className="iconBox"><Users size={17}/></div><span>Active candidates</span><b>{candidates.filter(c=>c.stage!=='HIRED'&&c.stage!=='REJECTED').length}</b></div><div className="summaryRight">{[...PIPELINE,'REJECTED' as Stage].map(s=><span key={s} className="summaryPill"><i className={`stageDot dot-${s.toLowerCase()}`}/>{LABEL[s]} <b>{candidates.filter(c=>c.stage===s).length}</b></span>)}</div></div>
 <section className="searchSection"><div className="searchHead"><div><h2>Find your next great hire</h2><p>Search by candidate, stage, history, or time in stage.</p></div><span className="searchHint">NATURAL LANGUAGE SEARCH</span></div><form className="searchBar" onSubmit={e=>{e.preventDefault();void search()}}><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try “Who’s in Interview right now?” or “sharam”…"/><kbd>↵</kbd></form><div className="suggestions">Try <button onClick={()=>{setQuery('Who’s in Interview right now?');void search('Who’s in Interview right now?')}}>Interview right now</button><span>·</span><button onClick={()=>{setQuery('Who has been stuck in Screening for more than a week?');void search('Who has been stuck in Screening for more than a week?')}}>Screening for a week</button><span>·</span><button onClick={()=>{setQuery('Everyone except rejected candidates');void search('Everyone except rejected candidates')}}>Exclude rejected</button></div></section>
 <div className="boardHeading"><div><h2>{searched?'Search results': 'Your hiring pipeline'}</h2><p>{searched?`${searched.results.length} matching candidates`:`${candidates.length} candidates across all stages`}</p></div><div className="boardActions"><span className="updated"><span className="liveDot"/> Updated just now</span><button className="viewButton">Board view <ChevronRight size={14}/></button></div></div>
 {searched&&!searched.results.length&&<div className="notice">{searched.message}</div>}{error&&<div className="notice errorNotice">{error}</div>}
 <div className="board">{[...PIPELINE,'REJECTED' as Stage].map((stage,index)=>{const list=shown.filter(c=>c.stage===stage);return <section className="column" key={stage}><div className="columnHeader"><div className="columnName"><i className={`stageDot dot-${stage.toLowerCase()}`}/><h3>{LABEL[stage]}</h3><span className="count">{list.length}</span></div><button className="more" aria-label={`More ${LABEL[stage]} options`}>···</button></div><div className="columnRule"/>{list.map(c=><article className="candidate" key={c.id}><div className="candidateTop"><div className={`initials initials-${index}`}>{c.name.split(' ').map(n=>n[0]).join('')}</div><button className="cardMore" onClick={()=>void details(c)}>···</button></div><button className="candidateName" onClick={()=>void details(c)}>{c.name}</button><div className="candidateEmail">{c.email}</div><div className="cardFooter"><span><Clock3 size={13}/>{Math.max(0,Math.floor((clock-Date.parse(c.updatedAt))/86400000))}d in stage</span><button className="nextButton" disabled={busy||index>=PIPELINE.length-1} title="Move one stage forward" onClick={()=>void move(c,PIPELINE[index+1])}><ArrowRight size={15}/></button></div><button className="rejectLink" onClick={()=>void move(c,'REJECTED')}>Reject candidate</button></article>)}{!list.length&&<div className="emptyColumn">No candidates here yet</div>}</section>})}</div>
 <footer><span>MINI HIRING PIPELINE</span><span>Candidate decisions, kept clear.</span><span>Local demo workspace</span></footer>
 {(modal||active)&&<div className="backdrop" onMouseDown={e=>{if(e.target===e.currentTarget){setModal(false);setActive(null)}}}>{modal&&<div className="dialog"><div className="dialogHead"><div><h2>Add candidate</h2><p>They’ll enter the pipeline at Applied.</p></div><button onClick={()=>setModal(false)}><X size={18}/></button></div><form onSubmit={e=>void add(e)}><label>Full name<input name="name" placeholder="e.g. Priya Sharma" required minLength={2} maxLength={100}/></label><label>Email address<input name="email" type="email" placeholder="name@example.com" required/></label>{error&&<div className="formError">{error}</div>}<button className="primary dialogSubmit" disabled={busy}>{busy?'Saving…':'Add to pipeline'} <ArrowRight size={16}/></button></form></div>}{active&&<aside className="drawer"><div className="dialogHead"><div><span className="searchHint">CANDIDATE PROFILE</span><h2>{active.name}</h2><p>{active.email}</p></div><button onClick={()=>setActive(null)}><X size={18}/></button></div><div className="profileStage"><i className={`stageDot dot-${active.stage.toLowerCase()}`}/><strong>{LABEL[active.stage]}</strong><span>Current stage</span></div><h3 className="historyHeading"><History size={16}/> Stage history</h3><div className="timeline">{events.map(ev=><div className="event" key={ev.id}><span className="eventDot"/><div><b>{ev.eventType==='CREATED'?'Candidate added':`${ev.fromStage?LABEL[ev.fromStage]+' → ':''}${LABEL[ev.toStage]}`}</b><time>{fmt(ev.createdAt)}</time></div></div>)}</div><div className="drawerDuration">In current stage for <b>{Math.max(0,Math.floor((clock-Date.parse(active.updatedAt))/86400000))} days</b></div></aside>}</div>}
 </main>
}
