import db from '../src/lib/db';
import {PIPELINE,type Stage} from '../src/lib/domain';
if((db.prepare('SELECT COUNT(*) AS count FROM candidates').get() as {count:number}).count){console.log('Database already contains candidates; leaving it unchanged.');process.exit(0);}
const now=Date.now();
const rows:[string,string,Stage,number,boolean][]=[['Priya Sharma','priya.sharma@example.test','SCREENING',10,false],['Aarav Mehta','aarav.mehta@example.test','APPLIED',1,false],['Maya Iyer','maya.iyer@example.test','INTERVIEW',0,false],['Rohan Das','rohan.das@example.test','OFFER',3,false],['Anika Bose','anika.bose@example.test','HIRED',5,false],['Kabir Shah','kabir.shah@example.test','REJECTED',6,false],['Nisha Rao','nisha.rao@example.test','SCREENING',2,false],['Dev Kapoor','dev.kapoor@example.test','INTERVIEW',8,false],['Tara Sen','tara.sen@example.test','APPLIED',3,false],['Ishaan Roy','ishaan.roy@example.test','OFFER',1,false],['Leela Menon','leela.menon@example.test','HIRED',20,false],['Vikram Jain','vikram.jain@example.test','OFFER',12,true],['Sara Khan','sara.khan@example.test','SCREENING',9,false],['Arjun Nair','arjun.nair@example.test','INTERVIEW',14,false],['Meera Gill','meera.gill@example.test','APPLIED',21,false],['Neel Verma','neel.verma@example.test','REJECTED',4,false]];
const insertCandidate=db.prepare('INSERT INTO candidates(name,email,stage,createdAt,updatedAt) VALUES(?,?,?,?,?)');
const insertEvent=db.prepare('INSERT INTO stage_events(candidateId,fromStage,toStage,eventType,createdAt) VALUES(?,?,?,?,?)');
const seed=db.transaction(()=>{for(const [name,email,target,age,rejectedAfterOffer] of rows){const final:Stage=rejectedAfterOffer?'REJECTED':target;const path=[...PIPELINE.slice(0,Math.max(1,PIPELINE.indexOf(target)+1))];if(rejectedAfterOffer)path.push('REJECTED');const entered=now-age*86400000;const created=entered-(path.length-1)*86400000;const id=Number(insertCandidate.run(name,email,final,new Date(created).toISOString(),new Date(entered).toISOString()).lastInsertRowid);let from:Stage|null=null;path.forEach((to,i)=>{const at=created+i*86400000;insertEvent.run(id,from,to,i===0?'CREATED':to==='REJECTED'?'REJECTED':'STAGE_MOVED',new Date(at).toISOString());from=to;});}});
seed();
console.log(`Seeded ${rows.length} fictional candidates with an audit timeline relative to seed time. Priya has been in Screening for 10 days.`);
